server:
  port: 8080

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/postgres
    username: postgres
    password: 12345
  jpa:
    hibernate:
      ddl-auto: update

  flyway:
    url: jdbc:postgresql://localhost:5432/postgres
    user: postgres
    password: 12345
#    schemas: public
#    baseline-version: 1
    baseline-on-migrate: true
    validate-on-migrate: false

springdoc:
  show-actuator: true
  use-management-port: false
  api-docs:
    path: "/api-docs"
  swagger-ui:
    groups-order: desc
    path: "/swagger-ui"
    disable-swagger-default-url: true
    operations-sorter: method
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'

jwt:
  header: Authorization
  secretKey: project
  jwtExpiration: 645004
logging:
#  level:
#    root: debug