spring:
  datasource:
    driver-class-name: org.h2.Driver

server:
  port: 8080
springdoc:
  show-actuator: true
  use-management-port: false
  api-docs:
    path: "/api-docs"
  swagger-ui:
    groups-order: desc
    path: "/swagger-ui"
    disable-swagger-default-url: true
    operations-sorter: method
  default-consumes-media-type: 'application/json'
  default-produces-media-type: 'application/json'